import 'package:blood_dontating_app/features/blood_donors/presentation/screens/blood_donors_screen.dart';
import 'package:blood_dontating_app/features/blood_request/presentation/screens/blood_requests_screen.dart';
import 'package:blood_dontating_app/features/create_post/presentation/screens/create_post_screen.dart';
import 'package:flutter/material.dart';

List<String> cities = [
  "Karachi",
  "Islamabad",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Gujranwala",
  "Sialkot",
  "Sargodha",
  "Bahawalpur",
  "Sheikhupura",
  "Jhelum",
  "Gujrat",
  "Kasur",
  "Okara",
  "Sahiwal",
  "Vehari",
  "Khanewal",
  "Lodhran",
  "Pakpattan",
  "Attock",
  "Chakwal",
  "Mandi Bahauddin",
  "Hafizabad",
  "Nankana Sahib",
  "Toba Tek Singh",
  "Jhang",
  "Chiniot",
  "Bhakkar",
  "Layyah",
  "Muzaffargarh",
  "Rahim Yar Khan",
  "Bahawalnagar",
  "Rajanpur",
  "Dera Ghazi Khan",
  "Taunsa",
  "Kot Addu",
  "Murree",

  "Hyderabad",
  "Sukkur",
  "Larkana",
  "Nawabshah",
  "Mirpurkhas",
  "Jacobabad",
  "Shikarpur",
  "Khairpur",
  "Dadu",
  "Thatta",
  "Badin",
  "Tando Adam",
  "Tando Allahyar",
  "Tando Muhammad Khan",
  "Jamshoro",
  "Umerkot",
  "Mithi",
  "Sanghar",
  "Ghotki",
  "Kandhkot",
  "Kashmore",
  "Peshawar",
  "Mardan",
  "Mingora",
  "Swat",
  "Abbottabad",
  "Mansehra",
  "Haripur",
  "Nowshera",
  "Swabi",
  "Charsadda",
  "Kohat",
  "Karak",
  "Bannu",
  "Lakki Marwat",
  "Dera Ismail Khan",
  "Tank",
  "Hangu",
  "Batkhela",
  "Timergara",
  "Dir",
  "Chitral",
  "Shangla",
  "Buner",
  "Quetta",
  "Gwadar",
  "Turbat",
  "Kech",
  "Panjgur",
  "Khuzdar",
  "Kalat",
  "Mastung",
  "Loralai",
  "Zhob",
  "Qila Saifullah",
  "Pishin",
  "Chaman",
  "Ziarat",
  "Dera Bugti",
  "Sibi",
  "Barkhan",
  "Kohlu",
  "Awaran",
  "Washuk",
  "Nushki",
  "Kharan",

  "Gilgit",
  "Skardu",
  "Hunza",
  "Nagar",
  "Ghizer",
  "Ghanche",
  "Diamer",
  "Astore",
  "Shigar",

  "Muzaffarabad",
  "Mirpur",
  "Kotli",
  "Bhimber",
  "Rawalakot",
  "Bagh",
  "Pallandri",
  "Hattian Bala",
  "Neelum",
];
List<String> bloodGroups = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
List<String> genders = ['Male', 'Female'];
List<String> decisions = ['Yes', 'No'];
final List<Map<String, String>> bloodGroupIcons = [
  {"label": "A+", "icon": "assets/blood_icons/a_pos.png"},
  {"label": "A-", "icon": "assets/blood_icons/a_neg.png"},
  {"label": "AB+", "icon": "assets/blood_icons/ab_pos.png"},
  {"label": "AB-", "icon": "assets/blood_icons/ab_neg.png"},
  {"label": "B+", "icon": "assets/blood_icons/b_pos.png"},
  {"label": "B-", "icon": "assets/blood_icons/b_neg.png"},
  {"label": "O+", "icon": "assets/blood_icons/o_pos.png"},
  {"label": "O-", "icon": "assets/blood_icons/o_neg.png"},
];
final List<Map<String, dynamic>> activitiesIcons = [
  {
    "label": "Blood Donors",
    "subtitle": "120 posts",
    "icon": Icons.bloodtype,
    "screen": BloodDonorsScreen(),
  },
  {
    "label": "Blood Requests",
    "subtitle": "50 posts",
    "icon": Icons.request_page,
    "screen": BloodNeededScreen(),
  },
  {
    "label": "Create Post",
    "subtitle": "New post",
    "icon": Icons.post_add,
    "screen": CreatePostScreen(),
  },
  {
    "label": "Blood Given",
    "subtitle": "100 donations",
    "icon": Icons.done_all,
    "screen": BloodNeededScreen(),
  },
];
