List<String> cities = [
  "Karachi",
  "Islamabad",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Gujranwala",
  "Sialkot",
  "Sargodha",
  "Bahawalpur",
  "Sheikhupura",
  "Jhelum",
  "Gujrat",
  "Kasur",
  "Okara",
  "Sahiwal",
  "Vehari",
  "Khanewal",
  "Lodhran",
  "Pakpattan",
  "Attock",
  "Chakwal",
  "Mandi Bahauddin",
  "Hafizabad",
  "Nankana Sahib",
  "Toba Tek Singh",
  "Jhang",
  "Chiniot",
  "Bhakkar",
  "Layyah",
  "Muzaffargarh",
  "Rahim Yar Khan",
  "Bahawalnagar",
  "Rajanpur",
  "Dera Ghazi Khan",
  "Taunsa",
  "Kot Addu",
  "Murree",

  "Hyderabad",
  "Sukkur",
  "Larkana",
  "Nawabshah",
  "Mirpurkhas",
  "Jacobabad",
  "Shikarpur",
  "Khairpur",
  "Dadu",
  "Thatta",
  "Badin",
  "Tando Adam",
  "Tando Allahyar",
  "Tando Muhammad Khan",
  "Jamshoro",
  "Umerkot",
  "Mithi",
  "Sanghar",
  "Ghotki",
  "Kandhkot",
  "Kashmore",
  "Peshawar",
  "Mardan",
  "Mingora",
  "Swat",
  "Abbottabad",
  "Mansehra",
  "Haripur",
  "Nowshera",
  "Swabi",
  "Charsadda",
  "Kohat",
  "Karak",
  "Bannu",
  "Lakki Marwat",
  "Dera Ismail Khan",
  "Tank",
  "Hangu",
  "Batkhela",
  "Timergara",
  "Dir",
  "Chitral",
  "Shangla",
  "Buner",
  "Quetta",
  "Gwadar",
  "Turbat",
  "Kech",
  "Panjgur",
  "Khuzdar",
  "Kalat",
  "Mastung",
  "Loralai",
  "Zhob",
  "Qila Saifullah",
  "Pishin",
  "Chaman",
  "Ziarat",
  "Dera Bugti",
  "Sibi",
  "Barkhan",
  "Kohlu",
  "Awaran",
  "Washuk",
  "Nushki",
  "Kharan",

  "Gilgit",
  "Skardu",
  "Hunza",
  "Nagar",
  "Ghizer",
  "Ghanche",
  "Diamer",
  "Astore",
  "Shigar",

  "Muzaffarabad",
  "Mirpur",
  "Kotli",
  "Bhimber",
  "Rawalakot",
  "Bagh",
  "Pallandri",
  "Hattian Bala",
  "Neelum",
];
List<String> bloodGroups = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
List<String> genders = ['Male', 'Female'];
List<String> decisions = ['Yes', 'No'];
